Add information about class mapper to docs
thecodingmachine/graphqlite pull request #358
Opened 2021-08-05 10:50 UTC by katakumby

I think it would be great to include information about setClassNameMapper property into docs as well

2021-08-06 00:25 UTC, oojacoboo commented
@katakumby Thanks for the PR.  I think under most circumstances this isn't a necessity at all.  Your composer autoload should take care of this.  Do you have a specific use case here?  Or, is this more about documenting the public API?  I'm not entirely opposed to this, but it does not need to be made so prominent in the config docs, and should be prefaced with information about Composer, the preferred way of handling the mapping.  We don't really want people abusing this.

2021-08-13 11:05 UTC, katakumby commented
This is more about documenting public API and you are right it don't have to be so prominent, in my case i needed to register custom directory because of customized non framework environment, when using that method i was able to properly integrate https://github.com/ThingEngineer/PHP-MySQLi-Database-Class existing models to support graphqlite in separated environment's with shared models, im doing it that way to have as less as possible dependencies across environments/apps.

2021-08-14 02:55 UTC, oojacoboo requested changes

2021-08-14 02:55 UTC, oojacoboo commented on website/versioned_docs/version-4.1/other_frameworks.md
> +//Add class mapper to map a class names to one or many possible file names according to PSR-0 or PSR-4
Please follow the comment code-style, space after `//`

2021-08-14 02:55 UTC, oojacoboo commented on website/versioned_docs/version-4.1/other_frameworks.md
> +$factory->setClassNameMapper(new ClassNameMapper());
Please move this further down the calls, ie. priority.

2021-08-31 12:26 UTC, oojacoboo commented
The docs have been updated quite a bit.  Please review for merging.

2021-08-31 12:26 UTC, closed without merging