fix: RecursiveTypeMapper returns exception which can't be handled by StandardServer
thecodingmachine/graphqlite pull request #646
Opened 2024-01-03 03:50 UTC by fogrye

RecursiveTypeMapper throws CannotMapTypeException when fails to find class by name. This exception goes through the GraphQl executor instead of catching and wrapping into ExecutionResult. Non wrapped exception does not trigger HttpCodeDecider. Schema test trust more to input than configuration which is not optimal, great possibility to improve configuration validation.

Fixes: #336

2024-01-03 04:01 UTC, oojacoboo commented
Thanks for this @fogrye.  That skipped test - can we get that resolved?  What's the issue with it?  I'm not seeing where it's using a request in that test either.

2024-01-03 04:20 UTC, fogrye commented
@oojacoboo it meant to fail when test query request entity which isn't presented because of bad config but after fix stoped. Now `doTestSchema` throws unexpected exception because `$result->toArray()` returns array without `data` key but with `errors`. 

I see there only option for rewrite: check that with bad config (like not existing folder) nothing happens or new exception been thrown.

2024-01-03 04:28 UTC, oojacoboo commented
Can we still use `CannotMapTypeException` and set the `Error` from the `createLocatedError` as the previous exception value?  Maybe by adding a new method like `CannotMapTypeException::createFromLocatedError`?

2024-01-03 04:35 UTC, fogrye commented
@oojacoboo unfortunately no, `GraphQL\Server\Helper` is too strict about types.

2024-01-03 05:11 UTC, oojacoboo commented
Why can't/shouldn't `CannotMapTypeException` just extend `GraphQL\Error\Error`?

2024-01-03 10:08 UTC, fogrye commented
@oojacoboo I see the point in keeping everything clean and consistent but here is some problems:
1. If `CannotMapTypeException` becomes a child of `Error` all  errors it constructs becomes "soft" and handled which is a big change.
2. All exceptions in `CannotMapTypeException` some way referred to dev's mistake while in case of `RecursiveTypeMapper` it's end of execution which deserves some "special attention".
3. Also `RecursiveTypeMapper` has nothing to take from it's possible parent and this extend just a bad inheritance.

Of course it's up to you to as I'm newbie here but I would wish to clean up mappings a little including rethinking about how they trigger errors. Like, as an example, currently there is no way to throw error with reference to place in gql request because mapper which triggers them know nothing about which node it's processing.

2024-01-03 21:41 UTC, oojacoboo commented
Good points @fogrye.  Let's find a way to preserve that test.  Maybe it makes sense to create a new Exception class for this scenario, then we can expect that Exception in that test commented out?

I agree that some improvements could be made on the mappings.  If you want to submit a PR that takes a shot at this, that'd certainly be appreciated.

2024-02-05 02:39 UTC, oojacoboo commented
@fogrye just a reminder on this.  It'd be nice to get this merged in before it gets stale.  We need tests though.

2024-02-05 21:46 UTC, fogrye commented
@oojacoboo had a busy time lately, will try to make it for tests soon.

2024-02-11 00:44 UTC, oojacoboo requested changes

2024-02-11 00:44 UTC, oojacoboo commented on tests/SchemaFactoryTest.php
> +    private function _doTestSchema(Schema $schema): ExecutionResult
Let's not name private methods with a leading underscore, this is a really outdated code style that's really no longer used.

2024-02-11 00:44 UTC, oojacoboo commented on src/Mappers/RecursiveTypeMapper.php
> +        throw TypeNotFoundException::createError($typeName);
An extra line before a throw statement is a good codestyle, much like a line before a return statement.

2024-02-11 00:45 UTC, oojacoboo commented
@fogrye thanks for this - couple small code style changes and I think it's ready to merge :)

2024-02-11 22:38 UTC, oojacoboo approved these changes

2024-02-11 22:38 UTC, merged