Fix prefetching the same GQL type for batch request
thecodingmachine/graphqlite pull request #658
Opened 2024-03-08 10:49 UTC by grynchuk

I have issue with getting wrong prefetch data while query in batch mode.  In short, first query prefetch specific data and set it to prefetch buffer, second query use previous query prefetch buffer instead of using its own and get incomplete data set. I have to note that this issue is relates to prefetching of nested data, see test for mo details.

2024-03-08 15:32 UTC, grynchuk commented on src/PrefetchBuffer.php
> +        mixed $info = null,
Should be ?ResolveInfo to avoid BC break, but it is disallowed by cs.

2024-03-11 02:38 UTC, oojacoboo requested changes
Thanks for the PR @grynchuk!  Everything looks pretty good - some CS fixes needed.

2024-03-11 08:13 UTC, grynchuk commented on tests/Fixtures/Integration/Models/Company.php
> + * @Type()
fixed

2024-03-11 08:13 UTC, grynchuk commented on tests/Fixtures/Integration/Types/ContactType.php
> +            if ([] === $contactPost) {
fixed

2024-03-11 08:14 UTC, grynchuk commented on tests/Fixtures/Integration/Types/PostType.php
> + * @ExtendType(class=Post::class)
fixed

2024-03-11 08:14 UTC, grynchuk commented on tests/Fixtures/Integration/Controllers/CompanyController.php
> +    /** @Query() */
ok

2024-03-11 08:14 UTC, grynchuk commented on tests/Fixtures/Integration/Types/ContactType.php
> +     * @Field()
fixed

2024-03-11 08:15 UTC, grynchuk commented on tests/Fixtures/Integration/Types/CompanyType.php
> + * @ExtendType(class=Company::class)
fixed

2024-03-11 22:05 UTC, oojacoboo approved these changes

2024-03-11 22:06 UTC, merged

2024-07-15 09:48 UTC, andrew-demb commented
@oojacoboo These fixes merged for the `7.x` version of graphqlite, but there's a major performance problem with `7.x` which is blocked update for `7.x` for the Symfony bundle -  https://github.com/thecodingmachine/graphqlite-bundle/pull/203#issuecomment-2201182492
And issue in graphqlite - https://github.com/thecodingmachine/graphqlite/issues/691

Would you approve PR with the same changes, but for `6.x` branch of graphqlite (and tag an additional `6.x` release after merge)?

2024-07-16 03:59 UTC, oojacoboo commented
@andrew-demb maybe it's just a better idea to test the changes in `class-finder` as per the comments in #691 and get that resolved, instead of just back patching, to prevent resolving the actual issue, assuming that you're even seeing any degraded performance.