Make the "smallest working example" actually work, see #553
thecodingmachine/graphqlite pull request #663
Opened 2024-03-14 15:15 UTC by shish

Make the "smallest working example" actually work, see #553

This example had implicit-and-undocumented dependencies on composer.json, and explicit-but-unexplained dependencies on "a container" and "a cache", leaving the installation and configuring of these as an exercise to the reader. I have changed it so that the example code can be copy-pasted verbatim, and the user will end up with an example which runs, which I find much easier to learn from :)

I'm still not actually sure if I'm doing this correctly, because #553 mentioned loading classes via the PSR-4 autoloader, and I found that it only worked when I manually listed out my controller classes inside the PSR-11 container, but it works...

2024-03-15 06:45 UTC, oojacoboo commented
Thanks for this @shish!

Let's stick with APCu in the example with a code comment for Filesystem, like #662.

2024-03-20 22:28 UTC, oojacoboo requested changes

2024-03-20 22:28 UTC, oojacoboo commented on website/docs/other-frameworks.mdx
> +    "thecodingmachine/graphqlite": "^6",
I think we can use an asterisk, `*` for the version here.  We're now at 7.0 - no need to specify.

2024-03-22 12:32 UTC, shish commented
(I do wonder if it'd be worth having example code as actual code (either in an "examples" folder, or a "graphqlite-examples" respository), rather than random code snippets inside a markdown text file -- that way we can use eg github actions to run the code and ensure that it both works and stays working 🤔 )

2024-04-03 06:03 UTC, oojacoboo commented
Let's update this PR such that the docs direct the reader to the examples, instead of maintaining any code here.

2024-04-19 03:09 UTC, oojacoboo commented
> Let's update this PR such that the docs direct the reader to the examples, instead of maintaining any code here.

@shish ^^

2024-12-18 10:12 UTC, oojacoboo commented
@shish would be nice to get this merged.  If you're giving up, I'll have to close it.

2025-03-26 04:09 UTC, closed without merging