Add psr-15 example to examples folder
thecodingmachine/graphqlite pull request #669
Opened 2024-03-22 12:53 UTC by shish

Add psr-15 example to examples folder

This example is broken and I don't know why (maybe somebody who knows what they are doing can explain?). But at least now we can _see_ that it is broken, which is better than just silently misleading people...

2024-04-03 06:01 UTC, oojacoboo requested changes

2024-04-03 06:01 UTC, oojacoboo commented on examples/psr-15/composer.lock
Don't commit the lock file - add to `.gitignore`

2024-04-23 14:19 UTC, shish commented
So this is failing and I don't know why :( I tried the same fix which worked for the no-framework example, but no luck

```
$ cd examples/psr-15
$ composer install
$ php -S 127.0.0.1:8080
```

```
$ curl -X POST -d '{"query":"{ hello(name: \"World\") }"}' -H "Content-Type: application/json" http://localhost:8080/graphql
{"errors":[{"message":"Cannot query field \"hello\" on type \"Query\".","locations":[{"line":1,"column":3}]}]}%  
```

2025-03-26 04:09 UTC, oojacoboo commented
Closing, as there doesn't seem to be any additional activity here.

2025-03-26 04:09 UTC, closed without merging